# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_remove_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
