# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_team_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
