# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20171001_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('isActive', models.BooleanField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
