# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
