# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_systemmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
