# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_ranking_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.TextField()),
                ('short_id', models.TextField()),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('author_name', models.TextField()),
                ('author_email', models.TextField()),
                ('authored_date', models.DateTimeField()),
                ('committer_name', models.TextField()),
                ('committer_email', models.TextField()),
                ('committed_date', models.DateTimeField()),
                ('path_with_namespace', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
