# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0008_sourcecommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
