# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0009_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecommit',
            name='author_login',
            field=models.TextField(default=','),
            preserve_default=False,
        ),
    ]
